name: haat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker:
  shared_preferences:
  dio: ^3.0.10
  rxdart: ^0.23.0
  flutter_bloc: ^3.2.0
  equatable:
  font_awesome_flutter:
  intl:
  awesome_dialog:
  image_cropper:
  flutter_launcher_icons:
  audioplayers:
  url_launcher:
  progress_dialog:
  connectivity:
  flutter_spinkit:
  kiwi:
  shimmer:
  adhara_socket_io: ^0.4.1
  firebase_messaging:
  cached_network_image:
  fancy_bottom_navigation:
  flutter_image_compress:
  bubble_bottom_bar:
  flutter_ringtone_player:
  flutter_app_badger:
  app_settings:
  flutter_slidable:
  loader_search_bar:
  geolocator: 5.1.3
  flutter_local_notifications:
  bubble:
  slide_countdown_clock:
  image_gallery_saver:
  toast:
  pin_code_fields:
  country_code_picker:
  ff_navigation_bar:
  curved_navigation_bar:
  carousel_pro:
  flutter_swiper:
  flutter_custom_clippers:
  multi_image_picker:
  google_maps_flutter:
  date_format:
  flutter_datetime_picker:
  esys_flutter_share:
  provider:
  fluttertoast:
  location:
  lottie:
  flutter_staggered_animations:
  webview_flutter:
  storage_path:
  transparent_image:
  flutter_chat_bubble:
  flutter_rating_bar:
  solid_bottom_sheet:
  modal_bottom_sheet:
  sliding_up_panel:
  video_player:
  camera:
  autocomplete_textfield:
  cupertino_icons:

dev_dependencies:

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/images/newLogo.png"
  image_path_ios: "assets/images/ios.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/langs/ar.json
    - assets/langs/en.json
  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: caira
      fonts:
        - asset: assets/fonts/cairo_regular.ttf